CREATE EXTENSION citext;

CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	name TEXT NOT NULL,
	username CITEXT UNIQUE NOT NULL,
	password TEXT NOT NULL,
	profile_pic TEXT NOT NULL
);

CREATE TABLE lists 